Repository Himashana/Maintenance-Alerts-WP-Plugin, pull requests merged in 2022-06, with the labels that each got.

#15 Updated: template1(.php) and minor changes
  bin/buildinfo.txt
  bin/trunk/Configuration.php
  bin/trunk/about.php
  bin/trunk/compatibility_check.php
  bin/trunk/compatibility_info.php
  bin/trunk/index.php
  bin/trunk/maintenance_mode.php
  bin/trunk/maintenance_screen.css
  bin/trunk/templates/Maintenance-Alerts-pt.php
  bin/trunk/templates/templates_styles.css
  src/index.php
  src/templates/Maintenance-Alerts-pt.php
  src/templates/templates_styles.css
Labels: enhancement, v1.2.0, Quality improvements, Normal change

#16 Finalized the version 1.2.0
  assets/icon-128x128.png
  assets/icon-256x256.png
  bin/assets/icon-128x128.png
  bin/assets/icon-256x256.png
  bin/buildinfo.txt
  bin/trunk/Configuration.php
  bin/trunk/compatibility_check.php
  bin/trunk/compatibility_info.php
  bin/trunk/index.php
  bin/trunk/maintenance_mode.php
  bin/trunk/maintenance_screen.css
  bin/trunk/readme.txt
  bin/trunk/templates/Maintenance-Alerts-pt.php
  bin/trunk/templates/templates_styles.css
  src/Configuration.php
  src/compatibility_check.php
  src/compatibility_info.php
  src/index.php
  src/maintenance_mode.php
  src/maintenance_screen.css
  src/readme.txt
  src/templates/Maintenance-Alerts-pt.php
  src/templates/templates_styles.css
Labels: documentation, enhancement, v1.2.0, Quality improvements, Normal change

#19 The new features not working in some systems issue has been fixed.
  bin/buildinfo.txt
  bin/trunk/compatibility_check.php
  bin/trunk/index.php
  bin/trunk/readme.txt
  src/compatibility_check.php
  src/index.php
  src/readme.txt
Labels: bug, good first issue, Normal change
